version: '3.8'

services:
  asset-management-database:
    container_name: asset-management-database
    image: postgres:latest
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - asset-management-network
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres

  # asset-manament-be: 
  #   build: .
  #   container_name: asset-management-be
  #   networks:
  #     - asset-management-network
  #   depends_on:
  #     - asset-management-database
  #   env_file:
  #     - .env

networks:
  asset-management-network:
    driver: bridge